import './style.css';
const api=(import.meta.env.VITE_API_URL || '').replace(/\/$/,'');
const won=n=>n.toLocaleString('ko-KR')+'원';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[], categories=[], selected=0, search='', enabled=false;
let cart=[]; try {cart=JSON.parse(localStorage.getItem('unnine-cart')||'[]').filter(x=>Number.isInteger(x.id)&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=100)}catch{}
function image(p){return `<img class="photo" src="${esc(p.image)}" alt="${esc(p.name)} 연출 사진" loading="lazy" decoding="async">`}
async function request(path,options){const r=await fetch(api+path,options);const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:'입력 내용을 확인해 주세요.');return data}
document.querySelector('#app').innerHTML=`<header><div class="top"><a href="#" class="logo" aria-label="언니네닭 홈"><img src="https://pub-236307febd5647328aae37b69df5373d.r2.dev/brand/unnine-logo-transparent.png" alt="언니네닭"></a><form id="search"><input aria-label="상품 검색" placeholder="어떤 상품을 찾으세요?"><button>검색</button></form><button id="cart-open">장바구니 <span id="count">0</span></button></div></header><main><section class="hero"><div><p class="accent">우리 집 식탁을 위한 장보기</p><h1>맛있는 선택,<br>언니네닭에서.</h1><p>닭고기부터 다양한 육류까지.<br>필요한 상품을 편리하게 만나보세요.</p><button id="browse">상품 둘러보기</button></div><img src="https://pub-236307febd5647328aae37b69df5373d.r2.dev/brand/hero-products.webp?v=2" alt="언니네닭 신선 육류 모음"></section><nav id="nav" class="category-nav" aria-label="상품 카테고리"></nav><section id="catalog"><div class="title"><h2 id="title">전체상품</h2><span id="results" aria-live="polite"></span></div><p id="error" role="alert"></p><div id="grid" class="grid"></div></section></main><footer>언니네닭 <p>상품·가격은 제공된 캡처를 바탕으로 등록한 초기 자료입니다. 상품 사진은 AI로 제작한 연출 이미지입니다.</p></footer><dialog id="cart"><div class="title"><h2>장바구니</h2><button id="cart-close" aria-label="닫기">닫기</button></div><div id="cart-lines"></div><p id="total"></p><form id="order"><h3>배송 정보</h3><label>받는 분<input name="customer_name" required maxlength="100" autocomplete="name"></label><label>연락처<input name="phone" required type="tel" pattern="0[0-9-]{8,19}" autocomplete="tel"></label><label>배송 주소<input name="address" required minlength="5" maxlength="500" autocomplete="street-address"></label><p>결제·배송비 연동 전입니다. 현재 기능은 결제 대기 상태의 주문 접수입니다.</p><button id="submit" type="submit">주문 접수</button><p id="order-message" role="status"></p></form></dialog>`;
function persist(){localStorage.setItem('unnine-cart',JSON.stringify(cart));document.querySelector('#count').textContent=cart.reduce((n,x)=>n+x.quantity,0)}
function render(){const filtered=products.filter(p=>(!selected||p.category_id===selected)&&p.name.includes(search));document.querySelector('#title').textContent=categories.find(c=>c.id===selected)?.name||'전체상품';document.querySelector('#results').textContent=filtered.length+'개 상품';document.querySelector('#grid').innerHTML=filtered.length?filtered.map(p=>`<article>${image(p)}<h3>${esc(p.name)}</h3><p>${esc(p.option)}</p><div class="price"><strong>${won(p.price)}</strong><button data-add="${p.id}" aria-label="${esc(p.name)} 장바구니 담기">담기</button></div></article>`).join(''):'<p class="empty">등록된 상품이 없습니다.</p>';document.querySelectorAll('[data-category]').forEach(e=>e.classList.toggle('active',+e.dataset.category===selected))}
function cartRender(){let total=0;document.querySelector('#cart-lines').innerHTML=cart.map(line=>{const p=products.find(p=>p.id===line.id);if(!p)return '';total+=p.price*line.quantity;return `<div class="line"><div>${esc(p.name)}<br><strong>${won(p.price)}</strong></div><label>수량<input type="number" min="1" max="100" value="${line.quantity}" data-quantity="${p.id}"></label><button data-remove="${p.id}">삭제</button></div>`}).join('')||'<p>장바구니가 비어 있습니다.</p>';document.querySelector('#total').textContent='상품 합계 '+won(total);document.querySelector('#submit').disabled=!enabled||!cart.length;document.querySelector('#submit').textContent=enabled?'주문 접수':'주문 준비 중';}
document.querySelector('#grid').addEventListener('click',e=>{const id=+e.target.closest('[data-add]')?.dataset.add;if(!id)return;const line=cart.find(x=>x.id===id);if(line)line.quantity=Math.min(100,line.quantity+1);else cart.push({id,quantity:1});persist();e.target.textContent='담았어요';setTimeout(()=>e.target.textContent='담기',900)});
document.querySelector('#nav').addEventListener('click',e=>{const button=e.target.closest('[data-category]');if(!button)return;selected=+button.dataset.category;render();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'})});
document.querySelector('#search').onsubmit=e=>{e.preventDefault();search=e.target.querySelector('input').value.trim();render();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'})};
document.querySelector('#browse').onclick=()=>document.querySelector('#catalog').scrollIntoView({behavior:'smooth'});
document.querySelector('#cart-open').onclick=()=>{cartRender();document.querySelector('#cart').showModal()};document.querySelector('#cart-close').onclick=()=>document.querySelector('#cart').close();
document.querySelector('#cart-lines').addEventListener('click',e=>{if(!e.target.dataset.remove)return;cart=cart.filter(x=>x.id!==+e.target.dataset.remove);persist();cartRender()});
document.querySelector('#cart-lines').addEventListener('change',e=>{if(!e.target.dataset.quantity)return;const line=cart.find(x=>x.id===+e.target.dataset.quantity);line.quantity=Math.max(1,Math.min(100,Math.trunc(+e.target.value)||1));persist();cartRender()});
document.querySelector('#order').onsubmit=async e=>{e.preventDefault();const button=document.querySelector('#submit'),message=document.querySelector('#order-message');button.disabled=true;message.textContent='주문 접수 중…';try{const values=Object.fromEntries(new FormData(e.target));const result=await request('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,items:cart.map(x=>({product_id:x.id,quantity:x.quantity}))})});cart=[];persist();cartRender();e.target.reset();message.textContent=`주문이 접수됐습니다. 번호 ${result.order_id} · 상품 합계 ${won(result.total)} · 결제 대기`;}catch(error){message.textContent=error.message;button.disabled=!enabled||!cart.length}};
function navButton(c){const img=c.image?`<img src="${esc(c.image)}" alt="" loading="lazy">`:'';return `<button type="button" class="cat" data-category="${c.id}">${img}<span>${esc(c.name)}</span></button>`}async function init(){try{if(!api)throw new Error('API 주소가 설정되지 않았습니다. VITE_API_URL을 설정해 주세요.');let allImage='';[categories,products,{orders_enabled:enabled,all_category_image:allImage}]=await Promise.all([request('/api/categories'),request('/api/products'),request('/api/config')]);cart=cart.filter(x=>products.some(p=>p.id===x.id));document.querySelector('#nav').innerHTML=[{id:0,name:'전체상품',image:allImage},...categories].map(navButton).join('');render();persist()}catch(error){document.querySelector('#error').textContent=error.message}}
persist();init();
