import './style.css';
const api=(import.meta.env.VITE_API_URL || '').replace(/\/$/,'');
const won=n=>n.toLocaleString('ko-KR')+'??;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let products=[], categories=[], selected=0, search='', enabled=false;
let cart=[]; try {cart=JSON.parse(localStorage.getItem('unnine-cart')||'[]').filter(x=>Number.isInteger(x.id)&&Number.isInteger(x.quantity)&&x.quantity>0&&x.quantity<=100)}catch{}
function image(p){return `<img class="photo" src="${esc(p.image)}" alt="${esc(p.name)} ?°ì¶œ ?¬ì§„">`}
async function request(path,options){const r=await fetch(api+path,options);const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:'?…ë ¥ ?´ìš©???•ì¸??ì£¼ì„¸??');return data}
document.querySelector('#app').innerHTML=`<header><div class="top"><a href="#" class="logo" aria-label="?¸ë‹ˆ?¤ë‹­ ??><img src="/assets/capture-2.jpg" alt="?¸ë‹ˆ?¤ë‹­"></a><form id="search"><input aria-label="?í’ˆ ê²€?? placeholder="?´ë–¤ ?í’ˆ??ì°¾ìœ¼?¸ìš”?"><button>ê²€??/button></form><button id="cart-open">?¥ë°”êµ¬ë‹ˆ <span id="count">0</span></button></div><nav id="nav" aria-label="?í’ˆ ì¹´í…Œê³ ë¦¬"></nav></header><main><section class="hero"><div><p class="accent">?°ë¦¬ ì§??íƒ???„í•œ ?¥ë³´ê¸?/p><h1>ë§›ìˆ??? íƒ,<br>?¸ë‹ˆ?¤ë‹­?ì„œ.</h1><p>??³ ê¸°ë????¤ì–‘???¡ë¥˜ê¹Œì?.<br>?„ìš”???í’ˆ???¸ë¦¬?˜ê²Œ ë§Œë‚˜ë³´ì„¸??</p><button id="browse">?í’ˆ ?˜ëŸ¬ë³´ê¸°</button></div><img src="https://pub-236307febd5647328aae37b69df5373d.r2.dev/products/chicken-breast-premium.png" alt="????´ì‚´ ?°ì¶œ ?¬ì§„"></section><section id="catalog"><div class="title"><h2 id="title">?„ì²´?í’ˆ</h2><span id="results" aria-live="polite"></span></div><p id="error" role="alert"></p><div id="grid" class="grid"></div></section></main><footer>?¸ë‹ˆ?¤ë‹­ <p>?í’ˆÂ·ê°€ê²©ì? ?œê³µ??ìº¡ì²˜ë¥?ë°”íƒ•?¼ë¡œ ?±ë¡??ì´ˆê¸° ?ë£Œ?…ë‹ˆ?? ?í’ˆ ?¬ì§„?€ AIë¡??œì‘???°ì¶œ ?´ë?ì§€?…ë‹ˆ??</p></footer><dialog id="cart"><div class="title"><h2>?¥ë°”êµ¬ë‹ˆ</h2><button id="cart-close" aria-label="?«ê¸°">?«ê¸°</button></div><div id="cart-lines"></div><p id="total"></p><form id="order"><h3>ë°°ì†¡ ?•ë³´</h3><label>ë°›ëŠ” ë¶?input name="customer_name" required maxlength="100" autocomplete="name"></label><label>?°ë½ì²?input name="phone" required type="tel" pattern="0[0-9-]{8,19}" autocomplete="tel"></label><label>ë°°ì†¡ ì£¼ì†Œ<input name="address" required minlength="5" maxlength="500" autocomplete="street-address"></label><p>ê²°ì œÂ·ë°°ì†¡ë¹??°ë™ ?„ì…?ˆë‹¤. ?„ì¬ ê¸°ëŠ¥?€ ê²°ì œ ?€ê¸??íƒœ??ì£¼ë¬¸ ?‘ìˆ˜?…ë‹ˆ??</p><button id="submit" type="submit">ì£¼ë¬¸ ?‘ìˆ˜</button><p id="order-message" role="status"></p></form></dialog>`;
function persist(){localStorage.setItem('unnine-cart',JSON.stringify(cart));document.querySelector('#count').textContent=cart.reduce((n,x)=>n+x.quantity,0)}
function render(){const filtered=products.filter(p=>(!selected||p.category_id===selected)&&p.name.includes(search));document.querySelector('#title').textContent=categories.find(c=>c.id===selected)?.name||'?„ì²´?í’ˆ';document.querySelector('#results').textContent=filtered.length+'ê°??í’ˆ';document.querySelector('#grid').innerHTML=filtered.length?filtered.map(p=>`<article>${image(p)}<h3>${esc(p.name)}</h3><p>${esc(p.option)}</p><div class="price"><strong>${won(p.price)}</strong><button data-add="${p.id}" aria-label="${esc(p.name)} ?¥ë°”êµ¬ë‹ˆ ?´ê¸°">?´ê¸°</button></div></article>`).join(''):'<p class="empty">?±ë¡???í’ˆ???†ìŠµ?ˆë‹¤.</p>';document.querySelectorAll('[data-category]').forEach(e=>e.classList.toggle('active',+e.dataset.category===selected))}
function cartRender(){let total=0;document.querySelector('#cart-lines').innerHTML=cart.map(line=>{const p=products.find(p=>p.id===line.id);if(!p)return '';total+=p.price*line.quantity;return `<div class="line"><div>${esc(p.name)}<br><strong>${won(p.price)}</strong></div><label>?˜ëŸ‰<input type="number" min="1" max="100" value="${line.quantity}" data-quantity="${p.id}"></label><button data-remove="${p.id}">?? œ</button></div>`}).join('')||'<p>?¥ë°”êµ¬ë‹ˆê°€ ë¹„ì–´ ?ˆìŠµ?ˆë‹¤.</p>';document.querySelector('#total').textContent='?í’ˆ ?©ê³„ '+won(total);document.querySelector('#submit').disabled=!enabled||!cart.length;document.querySelector('#submit').textContent=enabled?'ì£¼ë¬¸ ?‘ìˆ˜':'ì£¼ë¬¸ ì¤€ë¹?ì¤?;}
document.querySelector('#grid').addEventListener('click',e=>{const id=+e.target.closest('[data-add]')?.dataset.add;if(!id)return;const line=cart.find(x=>x.id===id);if(line)line.quantity=Math.min(100,line.quantity+1);else cart.push({id,quantity:1});persist();e.target.textContent='?´ì•˜?´ìš”';setTimeout(()=>e.target.textContent='?´ê¸°',900)});
document.querySelector('#nav').addEventListener('click',e=>{const button=e.target.closest('[data-category]');if(!button)return;selected=+button.dataset.category;render();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'})});
document.querySelector('#search').onsubmit=e=>{e.preventDefault();search=e.target.querySelector('input').value.trim();render();document.querySelector('#catalog').scrollIntoView({behavior:'smooth'})};
document.querySelector('#browse').onclick=()=>document.querySelector('#catalog').scrollIntoView({behavior:'smooth'});
document.querySelector('#cart-open').onclick=()=>{cartRender();document.querySelector('#cart').showModal()};document.querySelector('#cart-close').onclick=()=>document.querySelector('#cart').close();
document.querySelector('#cart-lines').addEventListener('click',e=>{if(!e.target.dataset.remove)return;cart=cart.filter(x=>x.id!==+e.target.dataset.remove);persist();cartRender()});
document.querySelector('#cart-lines').addEventListener('change',e=>{if(!e.target.dataset.quantity)return;const line=cart.find(x=>x.id===+e.target.dataset.quantity);line.quantity=Math.max(1,Math.min(100,Math.trunc(+e.target.value)||1));persist();cartRender()});
document.querySelector('#order').onsubmit=async e=>{e.preventDefault();const button=document.querySelector('#submit'),message=document.querySelector('#order-message');button.disabled=true;message.textContent='ì£¼ë¬¸ ?‘ìˆ˜ ì¤‘â€?;try{const values=Object.fromEntries(new FormData(e.target));const result=await request('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...values,items:cart.map(x=>({product_id:x.id,quantity:x.quantity}))})});cart=[];persist();cartRender();e.target.reset();message.textContent=`ì£¼ë¬¸???‘ìˆ˜?ìŠµ?ˆë‹¤. ë²ˆí˜¸ ${result.order_id} Â· ?í’ˆ ?©ê³„ ${won(result.total)} Â· ê²°ì œ ?€ê¸?;}catch(error){message.textContent=error.message;button.disabled=!enabled||!cart.length}};
async function init(){try{if(!api)throw new Error('API ì£¼ì†Œê°€ ?¤ì •?˜ì? ?Šì•˜?µë‹ˆ?? VITE_API_URL???¤ì •??ì£¼ì„¸??');[categories,products,{orders_enabled:enabled}]=await Promise.all([request('/api/categories'),request('/api/products'),request('/api/config')]);cart=cart.filter(x=>products.some(p=>p.id===x.id));document.querySelector('#nav').innerHTML=[{id:0,name:'?„ì²´?í’ˆ'},...categories].map(c=>`<button data-category="${c.id}">${esc(c.name)}</button>`).join('');render();persist()}catch(error){document.querySelector('#error').textContent=error.message}}
persist();init();
